# Generated by Django 3.2.8 on 2021-10-25 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211025_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2021, 10, 25), max_length=150, verbose_name='date of birth'),
            preserve_default=False,
        ),
    ]
